name: RoboPiDriver
channels:
  - conda-forge
dependencies:
  - python=3.9
  - opencv
  - pip
# pyserial (install using apt in raspbian
  - pip:
    - "--editable=git+https://github.com/pybluez/pybluez.git#egg=pybluez"
